/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se4de;

import javax.swing.*;

import java.awt.*;

public class App {
	static Rezeptbuch buch;
	// static Einkaufsliste liste;

	public static void main(String[] args) {
		// System.out.println(new App().getGreeting());
		buch = new Rezeptbuch();

		setupWindow();
	}

	static boolean setupWindow() {
		JFrame mainWindow = new JFrame("Koch-App");
		mainWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		mainWindow.setSize(800, 600);
		mainWindow.setResizable(false);
		JPanel mainPanel = new JPanel(new GridLayout(0, 2, 10, 10));
		JPanel rezeptPanel = new JPanel(new BorderLayout());
		JLabel rezeptLabel = new JLabel("Rezeptbuch", SwingConstants.CENTER);
		JButton rezeptButton = new JButton("Rezeptbuch öffnen");
		JPanel einkaufslistePanel = new JPanel(new BorderLayout());
		JLabel einkaufslisteLabel = new JLabel("Einkaufsliste", SwingConstants.CENTER);
		JButton einkaufslisteButton = new JButton("Einkaufsliste öffnen");

		rezeptPanel.add(rezeptLabel, BorderLayout.NORTH);
		rezeptPanel.add(rezeptButton, BorderLayout.CENTER);

		einkaufslistePanel.add(einkaufslisteLabel, BorderLayout.NORTH);
		einkaufslistePanel.add(einkaufslisteButton, BorderLayout.CENTER);

		mainPanel.add(rezeptPanel);
		mainPanel.add(einkaufslistePanel);

		mainPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

		mainWindow.getContentPane().add(mainPanel);

		mainWindow.setVisible(true);

		setupButtons(rezeptButton, einkaufslisteButton);

		return true;
	}

	static boolean setupButtons(JButton rButton, JButton eButton) {
		rButton.addActionListener(e -> {
			buch.init();
		});

		return true;
	}
}
