/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se4de;

import javax.swing.*;

import java.awt.*;

public class App {
	static Rezeptbuch buch;
	static Einkaufsliste liste;

	public static void main(String[] args) {
		buch = new Rezeptbuch();
		liste = new Einkaufsliste();

		setupWindow();
	}

	static void setupWindow() {
		JFrame mainWindow = new JFrame("Koch-App");
		mainWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		mainWindow.setSize(1100, 600);
		mainWindow.setResizable(false);
		JPanel mainPanel = new JPanel(new GridLayout(0, 2, 10, 10));
		JPanel rezeptPanel = new JPanel(new BorderLayout());
		JLabel rezeptLabel = new JLabel("Rezeptbuch", SwingConstants.CENTER);
		JButton rezeptButton = new JButton("Rezeptbuch \u00F6ffnen");
		JPanel einkaufslistePanel = new JPanel(new GridBagLayout());

		GridBagConstraints c = new GridBagConstraints();
		c.weightx = 1;
		c.weighty = 1;
		c.fill = GridBagConstraints.HORIZONTAL;

		JLabel einkaufslisteLabel = new JLabel("Einkaufsliste", SwingConstants.CENTER);
		c.gridx = 0;
		c.gridy = 1;
		c.gridheight = 1;
		c.anchor = GridBagConstraints.NORTH;
		einkaufslistePanel.add(einkaufslisteLabel, c);

		JButton einkaufslisteSave = new JButton("Speichern");
		c.gridx = 0;
		c.gridy = 2;
		c.gridheight = 1;
		c.anchor = GridBagConstraints.NORTH;
		einkaufslistePanel.add(einkaufslisteSave, c);

		JTextArea textArea = new JTextArea();
		c.gridx = 0;
		c.gridy = 3;
		c.gridheight = 2;
		c.weighty = 20.0;
		einkaufslistePanel.add(textArea, c);

		rezeptPanel.add(rezeptLabel, BorderLayout.NORTH);
		rezeptPanel.add(rezeptButton, BorderLayout.CENTER);

		textArea.setText(liste.set_inhalt());

		mainPanel.add(rezeptPanel);
		mainPanel.add(einkaufslistePanel);

		mainPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

		mainWindow.getContentPane().add(mainPanel);

		rezeptButton.addActionListener(e -> {
			JFrame rezeptBuchWindow = buch.init();
			rezeptBuchWindow.toFront();
			rezeptBuchWindow.requestFocus();
		});

		einkaufslisteSave.addActionListener(e -> liste.save(textArea.getText()));

		mainWindow.setVisible(true);
		mainWindow.toFront();
		mainWindow.requestFocus();

	}
}
