/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se4de;

import javax.swing.*;

import java.awt.*;

public class App {
	static Rezeptbuch buch;
	static Einkaufsliste liste;

	public static void main(String[] args) {
		// System.out.println(new App().getGreeting());
		buch = new Rezeptbuch();
		liste = new Einkaufsliste();

		setupWindow();
	}

	static boolean setupWindow() {
		JFrame mainWindow = new JFrame("Koch-App");
		mainWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		mainWindow.setSize(800, 600);
		mainWindow.setResizable(false);
		JPanel mainPanel = new JPanel(new GridLayout(0, 2, 10, 10));
		JPanel rezeptPanel = new JPanel(new BorderLayout());
		JLabel rezeptLabel = new JLabel("Rezeptbuch", SwingConstants.CENTER);
		JButton rezeptButton = new JButton("Rezeptbuch \u00F6ffnen");
		JPanel einkaufslistePanel = new JPanel(new GridLayout(3, 1, 10, 10));
		JPanel einkaufslisteGUIPanel = new JPanel(new BorderLayout());
		JPanel einkaufslisteCLIPanel = new JPanel(new BorderLayout());
		JPanel einkaufslisteCLISubPanel = new JPanel(new GridLayout(1, 0, 10, 10));
		JLabel einkaufslisteGUILabel = new JLabel("Einkaufsliste GUI", SwingConstants.CENTER);
		JLabel einkaufslisteCLILabel = new JLabel("Einkaufsliste CLI", SwingConstants.CENTER);
		JButton einkaufslisteGUIButton = new JButton("Einkaufsliste \u00F6ffnen");
		JButton einkaufslisteCLIPrintButton = new JButton("Einkaufsliste \n anzeigen");
		JButton einkaufslisteCLIAddButton = new JButton("Artikel \n hinzuf\u00FCgen");
		JButton einkaufslisteCLIDeleteButton = new JButton("Artikel \n entfernen");

		rezeptPanel.add(rezeptLabel, BorderLayout.NORTH);
		rezeptPanel.add(rezeptButton, BorderLayout.CENTER);

		einkaufslisteCLISubPanel.add(einkaufslisteCLIPrintButton);
		einkaufslisteCLISubPanel.add(einkaufslisteCLIAddButton);
		einkaufslisteCLISubPanel.add(einkaufslisteCLIDeleteButton);

		einkaufslisteGUIPanel.add(einkaufslisteGUILabel, BorderLayout.NORTH);
		einkaufslisteCLIPanel.add(einkaufslisteCLILabel, BorderLayout.NORTH);

		einkaufslisteGUIPanel.add(einkaufslisteGUIButton);
		einkaufslisteCLIPanel.add(einkaufslisteCLISubPanel);

		einkaufslistePanel.add(einkaufslisteGUIPanel);
		einkaufslistePanel.add(einkaufslisteCLIPanel);

		mainPanel.add(rezeptPanel);
		mainPanel.add(einkaufslistePanel);

		mainPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

		mainWindow.getContentPane().add(mainPanel);

		setupButtons(rezeptButton, einkaufslisteGUIButton, einkaufslisteCLIPrintButton, einkaufslisteCLIAddButton, einkaufslisteCLIDeleteButton);

		mainWindow.setVisible(true);
		mainWindow.toFront();
		mainWindow.requestFocus();

		return true;
	}

	static boolean setupButtons(JButton rButton, JButton eGUIButton, JButton eCLIPButton, JButton eCLIAButton, JButton eCLIDButton) {
		rButton.addActionListener(e -> {
			JFrame rezeptBuchWindow = buch.init();
			rezeptBuchWindow.toFront();
        	rezeptBuchWindow.requestFocus();
		});

		eGUIButton.addActionListener(e -> {
			JFrame einkaufslisteWindow = liste.init();
			einkaufslisteWindow.toFront();
        	einkaufslisteWindow.requestFocus();
		});

		eCLIPButton.addActionListener(e -> {
			liste.print();
		});

		eCLIAButton.addActionListener(e -> {
			liste.add_items();
		});

		eCLIDButton.addActionListener(e -> {
			liste.delete_items();
		});

		return true;
	}
}
